// <autogenerated>
//   This file was generated by T4 code generator AggregateRootScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Infrastructure.Seedwork.Domain;

namespace CAMP.AssetManagement.Domain.Model
{
	public sealed class ClassificationId : AbstractInt32Identity
	{
        public ClassificationId()
        {

        }

        public ClassificationId(int id)
        {
            Id = id;
        }

        public override string GetTag()
        {
            return "classification"; //TODO: change This
        }
	}
}
