// <autogenerated>
//   This file was generated by T4 code generator AggregateRootScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Runtime.Serialization;
using Infrastructure.Seedwork.Domain;

namespace CAMP.AssetManagement.Domain.Model
{
    public interface IClassificationCommand : IDomainCommand
    {
    }
 
    [DataContract]
	public class CreateClassificationCommand: IClassificationCommand
    {
        public ClassificationId ClassificationId { get; protected set; }
        public int ClassificationTypeId { get; protected set; }
        public string ClassificationName { get; protected set; }

        public CreateClassificationCommand(ClassificationId classificationId, int classificationTypeId, string classificationName)
        {
            ClassificationId = classificationId;
            ClassificationTypeId = classificationTypeId;
            ClassificationName = classificationName;
        }
    }
 
    [DataContract]
	public class AddClassificationLinkCommand: IClassificationCommand
    {
        public ClassificationId FromClassificationId { get; protected set; }
        public ClassificationId ToClassificationId { get; protected set; }

        public AddClassificationLinkCommand(ClassificationId fromClassificationId, ClassificationId toClassificationId)
        {
            FromClassificationId = fromClassificationId;
            ToClassificationId = toClassificationId;
        }
    }
 
    [DataContract]
	public class RemoveClassificationLinkCommand: IClassificationCommand
    {
        public ClassificationLinkId classificationLinkId { get; protected set; }

        public RemoveClassificationLinkCommand(ClassificationLinkId classificationLinkId)
        {
            classificationLinkId = classificationLinkId;
        }
    }
 
    [DataContract]
	public class AddTrackedSystemIdentifierCommand: IClassificationCommand
    {
        public ClassificationTrackedSystemId ClassificationTrackedSystemId { get; protected set; }
        public int TrackedSystemId { get; protected set; }
        public string LocalIdentifier { get; protected set; }

        public AddTrackedSystemIdentifierCommand(ClassificationTrackedSystemId classificationTrackedSystemId, int trackedSystemId, string localIdentifier)
        {
            ClassificationTrackedSystemId = classificationTrackedSystemId;
            TrackedSystemId = trackedSystemId;
            LocalIdentifier = localIdentifier;
        }
    }
}
